# Generated by Django 3.0.8 on 2020-09-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodafy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_space',
            name='amount_vehicles_current',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
