# Generated by Django 3.0.8 on 2020-09-26 17:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodafy', '0002_auto_20200926_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking_space',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 26, 19, 40, 42, 185339)),
        ),
    ]
