# Generated by Django 3.0.8 on 2020-09-29 15:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodafy', '0003_parking_space_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_space',
            name='amount_vehicles_current',
            field=models.IntegerField(blank=True, default='0', null=True),
        ),
        migrations.AlterField(
            model_name='parking_space',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 17, 13, 56, 139294)),
        ),
    ]
