# Generated by Django 3.0.8 on 2020-09-29 17:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodafy', '0005_auto_20200929_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking_space',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 29, 19, 2, 46, 116669)),
        ),
    ]
